/**
 * placement-hub.ts — hotspot geometry for the /psas installation (specs.md §4.3).
 *
 * GENERATED by scripts/make-placeholders.mjs. These percentages currently describe
 * the PLACEHOLDER composite in src/assets/placeholder/.
 *
 * When Stacey's real 3200×1800 + 1350×2400 compositions land, THIS FILE is the
 * only thing that changes: re-measure where each poster sits in her artwork and
 * update the percentages. Every hotspot, anchor, focus ring, and keyboard route
 * built against it keeps working untouched.
 *
 * Coordinates are % of the composite. Width is given; height is derived from the
 * canonical 4:5 ratio, so a hotspot can never drift out of the poster's shape.
 */

export interface Hotspot {
  /** Route slug — /psas/<slug>. */
  readonly slug: string;
  /** Full poster title. Becomes the anchor's accessible name (§4.3). */
  readonly title: string;
  /** Left edge, % of composite width. */
  readonly x: number;
  /** Top edge, % of composite height. */
  readonly y: number;
  /** Width, % of composite width. Height derives from 4:5. */
  readonly w: number;
}

/**
 * THE one art-direction boundary for the placement hub (§4.2, gate G18).
 *
 * Two consumers, one string: the wide `<source media>` attribute on the hub's
 * `<picture>`, and the client `matchMedia()` call that selects which hotspot
 * coordinate set is live. Never restate this query as a raw literal in the
 * hub's CSS or client code — a duplicated breakpoint lets the picture and the
 * hotspot selector disagree at the boundary, and a tap lands on the wrong
 * poster.
 */
export const PLACEMENT_HUB_WIDE_MEDIA = '(min-width: 768px)';

/** Art-directed source → hotspots. The portrait is an INDEPENDENT arrangement,
 *  never a crop of the wide master (§4.1) — hence two separate coordinate sets. */
export const placementHub = {
  wide: [
    { slug: 'confident-man', title: "A Clean Man Is A Confident Man", x: 4, y: 18, w: 17 },
    { slug: 'soap-smoldering', title: "Soap-Smoldering", x: 24, y: 30, w: 15 },
    { slug: 'unholy', title: "Unholy", x: 41.5, y: 12, w: 19 },
    { slug: 'redemption', title: "The Redemption Ad", x: 63, y: 28, w: 15.5 },
    { slug: 'thirst-announcement', title: "Public Thirst Announcement", x: 81, y: 16, w: 16 },
  ],
  portrait: [
    { slug: 'confident-man', title: "A Clean Man Is A Confident Man", x: 5, y: 5, w: 36 },
    { slug: 'soap-smoldering', title: "Soap-Smoldering", x: 55, y: 10, w: 34 },
    { slug: 'unholy', title: "Unholy", x: 12, y: 36, w: 40 },
    { slug: 'redemption', title: "The Redemption Ad", x: 60, y: 42, w: 32 },
    { slug: 'thirst-announcement', title: "Public Thirst Announcement", x: 26, y: 70, w: 42 },
  ],
} as const satisfies Record<'wide' | 'portrait', readonly Hotspot[]>;

/** Composite aspect ratios — reserve these to prevent layout shift (§11). */
export const compositeAspect = {
  wide: { w: 3200, h: 1800 },
  portrait: { w: 1350, h: 2400 },
} as const;

/** A hotspot's height in % of composite height, derived from the 4:5 ratio.
 *  Never hand-write a height: a wrong one silently misaligns the click target. */
export function hotspotHeight(w: number, source: 'wide' | 'portrait'): number {
  const a = compositeAspect[source];
  return ((w / 100) * a.w * 1.25 * 100) / a.h;
}
