// The Office's notices, verbatim from ../design.md §4, and the owner-approved fallback
// (docs/superpowers/specs/2026-09-29-office-error-site-design.md §3.5).
// tests/copy.test.mjs holds this file to those sources; change wording there, not here.
export const NOTICES = {
  first_access: [
    'OFFICE OF LATHER COMPLIANCE',
    'Establishment Directive 1961-A / Sub-Section 4',
    '',
    'NOTICE OF ADMINISTRATIVE CONTAINMENT',
    '',
    'The requested resource is unavailable.',
    'Access has been suspended under Regulatory Standard 41-B.',
    '',
    'A log entry has been created.',
    '',
    'Reference: 8804-X',
    'Current Status: RECORDING',
    '',
    'Please remain available.',
  ],
  same_session_refresh: [
    'REFRESH REQUEST DENIED',
    '',
    'Your previous notice remains in effect.',
    '',
    'Reference: 8804-X',
    'Status: UNCHANGED',
  ],
  later_return: [
    'OFFICE OF LATHER COMPLIANCE',
    'Establishment Directive 1961-A / Sub-Section 4',
    '',
    'NOTICE OF REPEAT ACCESS',
    '',
    'Terminal ID: [generated identifier]',
    'First Contact: [stored local timestamp]',
    'Secondary Contact: [current local timestamp]',
    'Reference: 8804-X',
    '',
    'Your prior administrative notice remains active.',
    '',
    'Current Status: RECORDING',
    '',
    'Please remain available.',
  ],
  continued_interest: [
    'NOTICE OF CONTINUED INTEREST',
    '',
    'You have accessed this resource [count] times.',
    '',
    'No further action is required from you.',
    'Please discontinue independent review.',
    '',
    'Reference: 8804-X',
    'Status: OBSERVED',
  ],
  fallback: [
    'OFFICE OF LATHER COMPLIANCE',
    'Establishment Directive 1961-A / Sub-Section 4',
    '',
    'NOTICE OF ADMINISTRATIVE CONTAINMENT',
    '',
    'The requested resource is unavailable.',
    'Access has been suspended under Regulatory Standard 41-B.',
    '',
    'Reference: 8804-X',
    '',
    'Please remain available.',
  ],
};
